In [1]:
import pandas as pd

# Cargamos el contenido del archivo en la variable df
df = pd.read_csv('cafe_sales.csv')

df.head(5)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

Hallazgos del archivo inicial

In [2]:
print(df.info())
print(df.isna().sum())
print(df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB
None
Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64
0

Sustitución de valores "ERROR" y "UNKNOWN" por NaN

In [5]:
df = df.replace(["ERROR", "UNKNOWN"], pd.NA)
print(df.info())
print(df.isna().sum())

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   str
 3   Price Per Unit    9467 non-null   str
 4   Total Spent       9498 non-null   str
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   str
dtypes: str(8)
memory usage: 625.1 KB
None
Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

Limpieza de Transaction ID

In [6]:
df["Transaction ID"].isna().sum()

np.int64(0)

Limpieza de Item

In [8]:
df["Item"].isna().sum()
df = df.dropna(subset=["Item"])

df["Item"].isna().sum()

np.int64(0)

In [10]:
print(df.isna().sum())

Transaction ID         0
Item                   0
Quantity             420
Price Per Unit       479
Total Spent          452
Payment Method      2877
Location            3583
Transaction Date     418
dtype: int64

Limpieza Quantity

In [15]:
# convertir la columna "Quantity" a tipo numérico
df["Quantity"] = pd.to_numeric(df["Quantity"], errors='coerce')

# eliminar nulos
df = df.dropna(subset=["Quantity"])

# convertir Quantity a entero
df["Quantity"] = df["Quantity"].astype(int)

print(df.isna().sum())
df.info()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit       464
Total Spent          432
Payment Method      2732
Location            3418
Transaction Date     396
dtype: int64
<class 'pandas.DataFrame'>
Index: 8611 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    8611 non-null   str
 1   Item              8611 non-null   str
 2   Quantity          8611 non-null   int64
 3   Price Per Unit    8147 non-null   str
 4   Total Spent       8179 non-null   str
 5   Payment Method    5879 non-null   str
 6   Location          5193 non-null   str
 7   Transaction Date  8215 non-null   str
dtypes: int64(1), str(7)
memory usage: 605.5 KB

Limpieza de Price Per Unit

In [17]:
# convertir la columna "Quantity" a tipo numérico
df["Price Per Unit"] = pd.to_numeric(df["Price Per Unit"], errors='coerce')

# eliminar nulos
df = df.dropna(subset=["Price Per Unit"])

print(df.isna().sum())
df.info()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit         0
Total Spent          415
Payment Method      2584
Location            3233
Transaction Date     374
dtype: int64
<class 'pandas.DataFrame'>
Index: 8147 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    8147 non-null   str
 1   Item              8147 non-null   str
 2   Quantity          8147 non-null   int64
 3   Price Per Unit    8147 non-null   float64
 4   Total Spent       7732 non-null   str
 5   Payment Method    5563 non-null   str
 6   Location          4914 non-null   str
 7   Transaction Date  7773 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 572.8 KB

Limpieza de Total Spent

In [ ]:
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors='coerce')
df.head(25)

# encontrar el valor de Total Spent
df["Total Spent"] = df["Total Spent"].fillna(
    df["Quantity"] * df["Price Per Unit"]
)

In [22]:
print(df.isna().sum())
df.info()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit         0
Total Spent            0
Payment Method      2584
Location            3233
Transaction Date     374
dtype: int64
<class 'pandas.DataFrame'>
Index: 8147 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    8147 non-null   str
 1   Item              8147 non-null   str
 2   Quantity          8147 non-null   int64
 3   Price Per Unit    8147 non-null   float64
 4   Total Spent       8147 non-null   float64
 5   Payment Method    5563 non-null   str
 6   Location          4914 non-null   str
 7   Transaction Date  7773 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 572.8 KB

Limpieza de Payment Method

In [ ]:
# eliminar nulos

df["Payment Method"].value_counts(dropna=False)
df = df.dropna(subset=["Payment Method"])

Payment Method
Digital Wallet    1863
Cash              1855
Credit Card       1845
Name: count, dtype: int64

Limpieza de Location

In [28]:
df["Location"].value_counts(dropna=False)

# eliminar nulos
df = df.dropna(subset=["Location"])
df["Location"].value_counts(dropna=False)

Location
In-store    1696
Takeaway    1693
Name: count, dtype: int64

In [29]:
print(df.isna().sum())
df.info()

Transaction ID        0
Item                  0
Quantity              0
Price Per Unit        0
Total Spent           0
Payment Method        0
Location              0
Transaction Date    155
dtype: int64
<class 'pandas.DataFrame'>
Index: 3389 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    3389 non-null   str
 1   Item              3389 non-null   str
 2   Quantity          3389 non-null   int64
 3   Price Per Unit    3389 non-null   float64
 4   Total Spent       3389 non-null   float64
 5   Payment Method    3389 non-null   str
 6   Location          3389 non-null   str
 7   Transaction Date  3234 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 238.3 KB

Limpieza de Transaction Date

In [32]:
df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"], 
    errors='coerce'
)

# eliminar nulos
df = df.dropna(subset=["Transaction Date"])

<class 'pandas.DataFrame'>
Index: 3389 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    3389 non-null   str
 1   Item              3389 non-null   str
 2   Quantity          3389 non-null   int64
 3   Price Per Unit    3389 non-null   float64
 4   Total Spent       3389 non-null   float64
 5   Payment Method    3389 non-null   str
 6   Location          3389 non-null   str
 7   Transaction Date  3234 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 238.3 KB

In [33]:
df.info()

<class 'pandas.DataFrame'>
Index: 3234 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    3234 non-null   str
 1   Item              3234 non-null   str
 2   Quantity          3234 non-null   int64
 3   Price Per Unit    3234 non-null   float64
 4   Total Spent       3234 non-null   float64
 5   Payment Method    3234 non-null   str
 6   Location          3234 non-null   str
 7   Transaction Date  3234 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 227.4 KB

Eliminar duplicados

In [34]:
df = df.drop_duplicates()
df.info()

<class 'pandas.DataFrame'>
Index: 3234 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    3234 non-null   str
 1   Item              3234 non-null   str
 2   Quantity          3234 non-null   int64
 3   Price Per Unit    3234 non-null   float64
 4   Total Spent       3234 non-null   float64
 5   Payment Method    3234 non-null   str
 6   Location          3234 non-null   str
 7   Transaction Date  3234 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 227.4 KB

Validar limpieza del DataFrame

In [35]:
print(df.info())
print(df.isna().sum())
print(df.duplicated().sum())

<class 'pandas.DataFrame'>
Index: 3234 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    3234 non-null   str
 1   Item              3234 non-null   str
 2   Quantity          3234 non-null   int64
 3   Price Per Unit    3234 non-null   float64
 4   Total Spent       3234 non-null   float64
 5   Payment Method    3234 non-null   str
 6   Location          3234 non-null   str
 7   Transaction Date  3234 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 227.4 KB
None
Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64
0

In [37]:
df.describe()

          Quantity  Price Per Unit  Total Spent            Transaction Date
count  3234.000000     3234.000000  3234.000000                        3234
mean      3.027211        2.954855     8.955164  2023-07-02 04:15:35.064935
min       1.000000        1.000000     1.000000         2023-01-01 00:00:00
25%       2.000000        2.000000     4.000000         2023-03-29 06:00:00
50%       3.000000        3.000000     8.000000         2023-07-06 00:00:00
75%       4.000000        4.000000    12.000000         2023-10-03 00:00:00
max       5.000000        5.000000    25.000000         2023-12-31 00:00:00
std       1.422675        1.296085     6.055905                         NaN

Carga de datos limpios

In [36]:
df.to_csv('cafe_sales_clean.csv', index=False)